name: igh-whatif
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.2.3
  - torchvision
  - pytorch
  - shap
  - flask
  - simplejson
  - flask-cors
  - waitress
  - pyaml
  - pytorch-lightning
